services:
  - type: web
    name: teaguard-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: DATABASE_URL
        value: postgresql+asyncpg://postgres.uypqhcslykxopdouxjgs:%40Rhewage3@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
